### ISSUE TITLE
Quickstart: fails to send messages when attempting to connect to an Iot Hub

### ISSUE THREAD

**Issue by atecce** [Azure/azure-event-hubs-go#110]
### Expected Behavior

"hello, world" appears in `stdout`

### Actual Behavior

`amqp: sender settlement mode "unsettled" requested, received "mixed" from server`

### Environment
- OS: 10.14.3
- Go version: 1.12.1
- Version of Library: 1.3.0

are IoT Hubs supported?

**Comment by devigned** [comment]
Hi @atecce, what region is your Event Hub in?

Per the IoT Hubs query, I think you found the open issue related to using IoT Hubs. Basically, we should make it easier to use IoT Hubs.

**Comment by atecce** [comment]
hai!

so this _is_ an IoT Hub, but I'm using the Event Hub compatible connection string, and it is in US East

**Comment by devigned** [comment]
I see. I need to add a IoT Hub resource to my test suite.

As a work around, you could use vcabbage/amqp `v0.10.4` rather than `v0.11.0`. In the `v0.11.0` release, [the library became more strict in link settlement mode negotiation](https://github.com/vcabbage/amqp/releases/tag/v0.11.0). In earlier versions, this error would not be raised.

**Comment by atecce** [comment]
ok! I'll play around with it

**Comment by atecce** [comment]
just curious was it [this pr](https://github.com/vcabbage/amqp/pull/157/files) that did it?

**Comment by devigned** [comment]
I believe so. I also think it was the correct course of action from the perspective of `vcabbage/amqp`. If the server and the client don't agree on link settlement, an app my run into undefined behavior.

**Comment by atecce** [comment]
oh totally. just wanted to see if I'm understanding things

fwiw when I add a 

```
[[override]]
  name = "pack.ag/amqp"
  version = "0.10.4"
```

to `Gopkg.toml` I get 

`context deadline exceeded`
`exit status 1`

**Comment by devigned** [comment]
hmm... give it a run with env: `DEBUG_LEVEL=3` and build with -tags debug. That should give you some pretty verbose protocol level output.

**Comment by atecce** [comment]
ah ok. same message

`amqp: sender settlement mode "unsettled" requested, received "mixed" from server`

**Comment by atecce** [comment]
hmmmm. getting the same thing actually

`amqp: sender settlement mode "unsettled" requested, received "mixed" from server`

and I'm _assuming_ this happens during the initial connection because I'm not seeing any debug output

**Comment by devigned** [comment]
Something doesn't seem right... I wouldn't expect this error with earlier versions of the amqp lib. Are you sure you rebuilt from a clean state? Do you need to run `go clean && go build -tags debug`?

**Comment by atecce** [comment]
ah ok. you are right. 

I was passing `-tags debug` on the execution of the binary and not the build bc I don't know how Go works apparently

getting lots of output now

**Comment by atecce** [comment]
ahha 

`13:54:55.831720 RX: Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:unauthorized-access, Description: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://iothub-ns-bar-1651822-ad94b7ec4c.servicebus.windows.net/bar'. TrackingId:af1521fd07b44158ae273150475bd094_G7, SystemTracker:gateway7, Timestamp:2019-05-21T17:54:55, Info: map[]}}`

so I'm using the `SharedAccessKey` for `iothubowner` right now and I'm wondering if that is the right move

**Comment by devigned** [comment]
Here's how the Python implementation handles creating a connection: https://github.com/Azure/azure-event-hubs-python/blob/9c80edb06bb3629e5f9c4ce9b091af561405a90b/azure/eventhub/client.py#L198-L225

**Comment by atecce** [comment]
heh. need to either enable a fallback route or set your own message route. closing
