### ISSUE TITLE
Potential socket leak in amqp connection

### ISSUE THREAD

**Issue by davidsnyder-jask** [Azure/azure-event-hubs-go#111]
https://github.com/Azure/azure-event-hubs-go/blob/95f9bc025a9462337f8087aa883bc9b35a1e693e/hub.go#L490

https://github.com/Azure/azure-event-hubs-go/blob/95f9bc025a9462337f8087aa883bc9b35a1e693e/hub.go#L510

We have a loop that calls `GetRuntimeInformation` to get a list of `PartitionIDs`. We've noticed that the number of sockets increases until the program crashes with `socket: too many open files`. These `newConnection` calls call `amqp.Dial()` which is not being closed. I believe you need `defer c.Close()` after each of these `newConnection` calls. 

### Expected Behavior

The number of TCP connections opened by the program should stay constant over time.

### Actual Behavior

The number of TCP connections is increasing unbounded.

### Environment
- OS: Darwin Kernel Version 18.2.0
- Go version:  go1.12.5 darwin/amd64
- Version of Library: github.com/Azure/azure-event-hubs-go v1.3.0

**Comment by devigned** [comment]
Oh no! That definitely needs to be cleaned up. Thank you for opening the issue.

**Comment by davidsnyder-jask** [comment]
Hi @devigned is there any timeline of when this fix would be available? We are considering forking the repo to add in the fix, but we'd rather not fork if we don't have to.

**Comment by devigned** [comment]
I'll get the fix in today and tag a new release. 

In the future, I'm also happy to accept a pull request with a fix as well. No need to run your own fork :).

**Comment by devigned** [comment]
should be good to go with `v1.3.1`

**Comment by davidsnyder-jask** [comment]
Fixed the issue we were seeing. Thanks so much!
