### ISSUE TITLE
SendBatch in v2 does not use partitionKey

### ISSUE THREAD

**Issue by MartinKosicky** [Azure/azure-event-hubs-go#128]
### Expected Behavior
When I send events in batches and those events have partitionKey set I expect all these events to go into the same partitionId.

### Actual Behavior
When I use SendBatch with the NewBatchIterator with a single event it always goes into random partition as if I did not set partitionKey for that event

### Environment
- OS: Ubuntu 18.04
- Go version: go version go1.12.7 linux/amd64
- Version of Library: github.com/Azure/azure-event-hubs-go/v2 v2.0.0

I am attaching a test case that does the following. Makes 100 batches where each batch has always exactly the same event with the same partitionKey. It also reads the partitions and prints which partition gets data. As you can see the event went into random partitions. This is imo a serious problem and we cannot use this library in production
```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"

	eventhub "github.com/Azure/azure-event-hubs-go/v2"
)

type partition_reader struct {
	partitionId string
}

func (s *partition_reader) handler(c context.Context, event *eventhub.Event) error {
	fmt.Println(s.partitionId, string(event.Data))
	return nil
}

func read_partitions(ctx context.Context, hub *eventhub.Hub) {
	// listen to each partition of the Event Hub
	runtimeInfo, err := hub.GetRuntimeInformation(ctx)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, partitionID := range runtimeInfo.PartitionIDs {
		// Start receiving messages
		//
		// Receive blocks while attempting to connect to hub, then runs until listenerHandle.Close() is called
		// <- listenerHandle.Done() signals listener has stopped
		// listenerHandle.Err() provides the last error the receiver encountered

		handler_obj := &partition_reader{
			partitionId: partitionID,
		}

		_, err := hub.Receive(ctx, partitionID, handler_obj.handler, eventhub.ReceiveWithLatestOffset())
		if err != nil {
			fmt.Println(err)
			return
		}
	}
}

func main() {
	connStr := "Endpoint=****"
	hub, err := eventhub.NewHubFromConnectionString(connStr)

	if err != nil {
		fmt.Println(err)
		return
	}

	ctx := context.Background()

	read_partitions(ctx, hub)

	for i := 0; i < 100; i++ {
		evt := eventhub.NewEventFromString("{\"haha\":1}")

		pk := "pk1"
		evt.PartitionKey = &pk
		batch := eventhub.NewEventBatchIterator(evt)
		err = hub.SendBatch(ctx, batch)
		if err != nil {
			log.Fatal(err)
		}
	}

	// Wait for a signal to quit:
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, os.Kill)
	<-signalChan
}
```

**Comment by MartinKosicky** [comment]
Probabbly the api of NewEventBatchIterator should expect a partitionKey as argument if there is a constraint that all events have same partitionId. Or I should be able to send any partition key in any event in the batch and it should work correctly. The implementation does not seem to be so flexible

**Comment by MartinKosicky** [comment]
Nothing? Is this intention that core functionality doesnt work?

**Comment by devigned** [comment]
I replied in a previous thread here: https://github.com/Azure/azure-event-hubs-go/issues/127#issuecomment-519487485

I feel that the batcher is working as it was designed without regard to partition key on individual events to make it easier to send batches. We found the partition batch error to be difficult for consumers to understand.

There are options for how this can be extended in the future. I’m happy to discuss how batches should be handled with partition keys.

One option that I was leaning toward would use the event iterator to iterate over events building a map by partition key and then send partitioned batches to the specified portion. Thoughts?

/cc @gavinfish

**Comment by MartinKosicky** [comment]
Hmmm I don't know the right answer to this question but I know the following:

- It worked in previous version of eventhub (don't know the exact tag, back when SendBatch was using EventBatch not the Iterator. It was clear that I am sending EventBatch to a specific partition, so there was not really any error.

- If I make a custom EventBatchIterator and return EventBatch on Next() and set the PartitionKey on the batch it still doesnt work (It's like the ampq message of EventBatch is missing PartitionKey) in new version

- If I don't have ability to send batches to partition key you are over assuming that people don't need it. However people who need it have no choice but to use Send (single message). These people will get hurt by performance the most because they actually had the use case to use batch.

- I like your idea that the iterator would build a map of events and then send them. People who need this use case would have to do it anyway, so you will eliminate other people having to write it.

Also if there will be still objections about sending batches to partitions, at least proabbly there should be a fix that EventBatch partitionKey will be used when creating AMPQ message and we will create our own implementation of EventBatchIterator, but currently we can only send one by one. If these problems won't get fixed we are also considering starting to use the eventhub REST API which has this functionality to send a batch to a partition key, but the ampq version seems better if possible.

**Comment by devigned** [comment]
- Previously, if you sent an EventBatch to a partition, it would work. That is, it would send all events to that partition without regard to the partition key on the event. I felt behavior was misleading / broken.
- You are 100% correct: https://github.com/Azure/azure-event-hubs-go/blob/master/batch.go#L166. The batch does not have the partition key property set when it is transformed into an AMQP message.
- Agreed. The worse case performance of batching even with a partitioned iterator will be about equal to single message.
- 👍 

> Also if there will be still objections about sending batches to partition keys, at least proabbly there should be a fix that EventBatch partitionKey will be used when creating AMPQ message and we will create our own implementation of EventBatchIterator, but currently we can only send one by one. If these problems won't get fixed we are also considering starting to use the eventhub REST API which has this functionality to send a batch to a partition key, but the ampq version seems better if possible.

There are no objections to adding to the existing functionality. I just want to make sure we get the right abstraction and solve the problem in the best way possible.

I don't recommend using the http endpoint. I think you will find the performance is lacking. The AMQP endpoint is the native endpoint for Event Hubs.

We also accept pull requests. If you feel strongly about a feature or implementation, we are delighted to discuss and review pull requests.

 > Maybe some last thoughts, if you gave people the ability to SendBatch(EventBatch) and also SendBatch(EventBatchIterator) 2 variants, it might be helpful. However if EventBatchIterator does roundrobin, you should panic if events have PartitionKey set so people don't make a mistake to use it and expect it to work (as I did)

Rather than the two methods, I would prefer to do the right thing. In the case of EventBatch serialization to an AMQP message, we should change that to respect properties set on the batch and ensure they are added to the AMQP message.

I don't think we'd panic, but definitely provide back an error :). Regardless, this case should not be an issue if we have a partitioned iterator.

**Comment by MartinKosicky** [comment]
Well I would vote to at least fix that the EventBatch gets PartitionKey when transformed to the AMPQ message as a priority so we would be able to at least workaround this by making implementation of the EventBatchITerator interface in short-term. I would submit pull request but I don't know if there is any AMPQ protocol documented publicly.  (It's hard to find such documentation)

And the SendBatch that would iterate and create a map per partition key would be the ultimiate solution for us.

**Comment by MartinKosicky** [comment]
hmm.. so what can we do here? Do you see any timeframe? Or you have any docs about AMPQ messages in eventhub? I can make pull request too

**Comment by devigned** [comment]
@gavinfish I'm hoping you can provide some guidance on when you think this work could be done.

**Comment by gavinfish** [comment]
@MartinKosicky I have created a PR to try to mitigate this issue at #134, feel free to have a try and give any feedback, thanks.

**Comment by MartinKosicky** [comment]
@gavinfish thank you very much,  i will try it today
