### ISSUE TITLE
When receiving PartitionID = nil

### ISSUE THREAD

**Issue by gfha** [Azure/azure-event-hubs-go#131]
### Expected Behavior
I expect to read out partition id, but get nil.

### Actual Behavior
spew dump of eventhub.SystemProperties

(*eventhub.SystemProperties)(0xc0002af680)({
 SequenceNumber: (*int64)(0xc000391790)(1220190),
 EnqueuedTime: (*time.Time)(0xc00045b060)(2019-08-08 07:01:41.582 +0000 UTC),
 Offset: (*int64)(0xc000391798)(292067211376),
 PartitionID: (*int16)(<nil>),
 PartitionKey: (*string)(<nil>)
})

### Environment
- OS: Windows 10
- Go version: 1.12.7
- Version of Library:  2.0.0

**Comment by gavinfish** [comment]
@gfha could you please provide any code to reproduce this issue?

**Comment by gfha** [comment]
Sure, it's really just the hello world,

https://gist.github.com/gfha/8e650643125ab4f79269bac6711404ba

**Comment by aloysiustany** [comment]
I am facing the same problem. Any update on this @gavinfish @gfha ?

**Comment by catalinaperalta** [comment]
We added documentation for this in #147 .  PartitionID will always be nil in the SystemProperties struct, this field was mistakenly added and was never part of the payload. If we ever do a new major release we will remove this field. 

I will close this issue now.
