### ISSUE TITLE
BatchWithMaxSize continuous loop if events exceed MaxSize

### ISSUE THREAD

**Issue by t-sean** [Azure/azure-event-hubs-go#146]
### Expected Behavior

When MaxSize is reached, I expect it to continue the loop at the next event position

### Actual Behavior

Continuously loops starting at the first event provided from NewEventBatchIterator

### Environment
- OS: Windows
- Go version: 1.12
- Version of Library: v2.0.3

Able to fix locally by storing a start position from ebi.Cursors last cursor value
```golang
func (ebi *EventBatchIterator) Next(eventID string, opts *BatchOptions) (*EventBatch, error) {
	var key string
	var start int
	for partitionKey, cursor := range ebi.Cursors {
		if cursor != len(ebi.PartitionEventsMap[partitionKey]) {
			key = partitionKey
			start = cursor
		}
	}
	...
	for _, event := range events[start:] {
        ...
```

**Comment by catalinaperalta** [comment]
Fixed in #198.
