### ISSUE TITLE
Handling of errors in event processing seems to be broken

### ISSUE THREAD

**Issue by Hades32** [Azure/azure-event-hubs-go#155]
My expectation when consuming events with the EPH was that, when a handler fails to process a message, it would not continue to process messages on this partition. Otherwise it would essentially skip a message what could lead to invalid states.

But when my handler, that I register like this
```
hub.RegisterHandler(timeoutCtx, e.handleEvent)
```

returns an error, this seems to be ignored, which is validated by looking at this line:
https://github.com/Azure/azure-event-hubs-go/blob/403470e62008fbcfef68ca1955b2ab123441ec69/eph/eph.go#L442

Nobody seems to do something useful with the error although that internal function could return errors...

Also the `wg.Done()` a few lines up should be in a `defer`. And maybe even handle panics, as the EPH is kind of a server.

Are my assumptions correct, or am I just missing something?

**Comment by devigned** [comment]
After reviewing this code, I believe you are correct on each account. The handler should return all errors from the composite handler and deal with them appropriately.

Great observation about the wg. To ensure execution, it should be in a defer.

If you are interested in a PR, please don't hesitate to open one. I'm sure it would gladly reviewed and accepted.

**Comment by Hades32** [comment]
Done, but I didn't touch the handling of panics in the handlers as I felt this might need deeper consideration.

**Comment by jhendrixMSFT** [comment]
Fixed in v3.1.2, thanks for your contribution :)
