### ISSUE TITLE
Unexpected type for amqp message annotation for key "x-opt-offset"

### ISSUE THREAD

**Issue by sheitm** [Azure/azure-event-hubs-go#159]
### Overview
This error happens when using the event processor host.

Please see the file azure-event-hubs-go -> event.go line 88 (in func GetCheckpoint).

```
func (e *Event) GetCheckpoint() persist.Checkpoint {
	var offset string
	var enqueueTime time.Time
	var sequenceNumber int64
	if val, ok := e.message.Annotations[offsetAnnotationName]; ok {
		offset = val.(string)
	}
```

### Expected Behavior
The expected behavior is that the object in the annotations map at the key offsetAnnotationName (== "x-opt-offset") is a string, and that the type assertion `offset = val.(string)` works without problems. 

### Actual Behavior
Sometimes `e.message.Annotations[offsetAnnotationName]` does not return a string, but an int64, and the application panics with the message:

This behavior seems to occur at random intervals, but usually happens relatively early after startup. I have not been able to determine why this sometimes happens, and whether I can prevent it somehow or if this is a bug in the library.

### Environment
- OS: Windows 10.0.18362 (error is reproduced in Docker image based on alpine:3.10)
- Go version: go1.13.6 windows/amd64
- Version of Library: v3

**Comment by catalinaperalta** [comment]
Fixed in #183.
