### ISSUE TITLE
[Question][Docs/Sample] EPH - Receive messages from single partition.

### ISSUE THREAD

**Issue by ksivamuthu** [Azure/azure-event-hubs-go#167]
I'm looking for a sample/docs to receive messages from a specific partition.  I looked at the sample using the event hub. 

But, Is there any sample/docs - where I can subscribe to the messages from a specific partition using EPH by claiming ownership of the partition. 

similar to this...
https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/eventhub/event-hubs#consume-events-from-a-single-partition

https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/src/eventHubConsumerClient.ts#L414-L422

**Comment by fafg** [comment]
hi @ksivamuthu, in this session you can find an example of how to do it...

https://github.com/Azure/azure-event-hubs-go#quick-start

you can left out that for and use something like this:
```go
 var partition = "0"
		// Start receiving messages 
		// 
		// Receive blocks while attempting to connect to hub, then runs until listenerHandle.Close() is called 
		// <- listenerHandle.Done() signals listener has stopped
		// listenerHandle.Err() provides the last error the receiver encountered 
		listenerHandle, err := hub.Receive(ctx, partition, handler, eventhub.ReceiveWithLatestOffset())
		if err != nil {
			fmt.Println(err)
			return
		}
```

**Comment by ksivamuthu** [comment]
Thanks.
