### ISSUE TITLE
checkpointing inconsistency across azure implementations 

### ISSUE THREAD

**Issue by obeyda** [Azure/azure-event-hubs-go#170]
# Context
![image](https://user-images.githubusercontent.com/15065966/79055115-44ab8a80-7c42-11ea-8bbb-6ebf806a1910.png)

i've used three ways to process events and do checkpointing: 
  - Azure.Messaging.EventHubs.EventProcessorClient class [.net] (red)
  - IoTHubTrigger for azure functions (blue)
  - azure-event-hubs-go library (green)
and i ended up with the structure shown in the screenshot (yellow is for deprecated `Microsoft.Azure.EventHubs`).

## Actual Behavior
Despite giving the same blob container do do checkpointing and leasing, the result is that each implementation does it in a different way: 
### Path:
  -  Azure.Messaging.EventHubs.EventProcessorClient: 
    it creates this structure: 
        1. for checkpoints: `iothub-ns-{hubname}-<number>.servicebus.windows.net}/{hubname}/{consumerGroup(to lowercase)}/checkpoint`
       2. for ownership: `iothub-ns-{hubname}-<number>.servicebus.windows.net}/{hubname}/{consumerGroup(to lowercase)}/ownership`
  - IoTHubTrigger for azure functions
    1. checkpoints: `iothub-ns-{hubname}-<number>.servicebus.windows.net}/{hubname}/{consumerGroup(normal case)}`
  - azure-event-hubs-go: in the root of the given blob container
### written data:
  - Azure.Messaging.EventHubs.EventProcessorClient: 
     1. different directories and files for checkpoints and ownership
     2. checkpointing and ownership data is written in the blob's metadata
  - IoTHubTrigger for azure functions: 
     1. same file for checkpointing and ownership
     2. checkpointing data is written in the blob, ownership data is written in the blob's metadata
  - azure-event-hubs-go:
     1. same file for checkpointing and ownership
     2. checkpointing and ownership data is written in the blob

## Expected behaviour

consistency across libraries, that's what a user would expect.

**Comment by obeyda** [comment]
if this is not the place to post this issue I would appreciate pointing me to where i can post it.

**Comment by nicolasGab** [comment]
Hi @obeyda I have come across the same inconsistency, having C# and Golang consumers. I've made a pull request to begin to address this, I would love your feedback.

**Comment by catalinaperalta** [comment]
Hi @nicolasGab! What version of the C# SDK are you using? I think with the new version even fixing the checkpointing location, there may still be some incompatibility: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-event-processor-checkpoints. Let me know what you think!

**Comment by TonioOoOo** [comment]
Hi @catalinaperalta,
 @nicolasGab' merge request uses the same path as the C # `Azure.Messaging.EventHubs` with the  `Azure.Messaging.EventHubs.Processor.EventProcessorClient`. In the C# lib, the Blob checkpointer use EventHub namespace, name and the consumer group name with the partition. This path prevent same consumer group name on different event hub to erase infos. It's a first step.

You think before merge this request, the second step is to store "offset" and "sequenceNumber" in blob metadatas and create an "ownership" blob with the property owner in ownerid metadata ?

Data in the current GO blob is interesting for debugging and not available in C # (enqueueTime and Epoch). We could keep the content of the main blob by adding metadata for compatibility ...

**Comment by devigned** [comment]
Do you intend on using the clients side by side on the same hub / consumer group, or is this simply to have the file structure look the same across implementations?

Is there a functional problem or is this more esthetic?

**Comment by nicolasGab** [comment]
Hi @devigned, our goal is to have the same file structure for offsets across implementations that may be in C#, Golang, Java, etc. on many eventhubs (and usually a consumer group is used by only one app, so only one implementation).

We would like to have an "offset" container in our storage account, aggregating checkpoints for all consumers for each of our hubs. This would be especially useful for automated checkpoint monitoring. This is definitely a functional problem for us.

At the moment, we find ourselves with nicely structured checkpoints for our C# implementations on one side, and checkpoint files all over the place for our Golang implementation on the other.

**Comment by catalinaperalta** [comment]
Closing this since the `WithPrefixInBlobPath` LeaserCheckpointerOption was added in #199. This should allow customization of blob paths.
