### ISSUE TITLE
Custom AMQP annotations cannot be sent/received

### ISSUE THREAD

**Issue by princjef** [Azure/azure-event-hubs-go#173]
Raw AMQP messages have an [Annotations](https://pkg.go.dev/github.com/Azure/go-amqp?tab=doc#Annotations) map which can contain arbitrary key/value pairs. This map is used by both Event Hubs and IoT Hub to set their own pieces of metadata, but it is also used by other systems and can be interacted with directly when working with other languages. As a result, other systems may produce or expect additional data in the annotations beyond the specific list provided by IoT Hub and Event Hubs.

### Expected Behavior

Custom annotations can be sent and received in the corresponding [Event](https://pkg.go.dev/github.com/Azure/azure-event-hubs-go/v3?tab=doc#Event) payload, regardless of whether they are part of the built-in ones placed in the [SystemProperties](https://pkg.go.dev/github.com/Azure/azure-event-hubs-go/v3?tab=doc#SystemProperties) struct.

### Actual Behavior

Only a restricted subset of annotations are placed in the [SystemProperties](https://pkg.go.dev/github.com/Azure/azure-event-hubs-go/v3?tab=doc#SystemProperties) struct. The rest of the annotations are hidden from the user and can neither be set nor retrieved.

### Environment
- OS: All (tested on WSL, MacOS)
- Go version: 1.13
- Version of Library: 3.2.0

**Comment by princjef** [comment]
I'm happy to work up a PR if this seems like a reasonable addition. The least invasive approach I can think of is to provide the raw map alongside the `SystemProperties` in the `Event` struct. When receiving, the map is presented raw (as with `ApplicationProperties` in the `Properties` field today), while during sending it is used as a base on which the `SystemProperties` fields get applied.

**Comment by princjef** [comment]
@jhendrixMSFT @gavinfish any thoughts on this?

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.  Fixed in v3.3.0
