### ISSUE TITLE
On batch of 10k and more events. I get invalid consumed number of rows in adx table

### ISSUE THREAD

**Issue by rnitzan** [Azure/azure-event-hubs-go#177]
### Expected Behavior
Sending 10k events with routing info for azure data explorer table, I should get matched 10k rows in the azure data explorer table

### Actual Behavior
In azure data explorer table i get 120k rows, where first 6k rows are duplicated many times and last 4k are missing at all.

This reproduced every time for 10k and more tables for at least csv/json data format were events include routing info.

If I removed routing info and set them in ingest connection for ADX https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub, then its OK and for sending 10k batch i get 10k rows as expected.
 
Client code:

    hub, err := eventhubs.NewHubFromConnectionString(connStr)

    var eventsBatch []*eventhubs.Event

    for _, event := range events {
        eventData := eventhubs.NewEvent(event)
        eventData.Set("Table", tableName)
        eventData.Set("IngestionMappingReference", mappaingName)
        eventData.Set("Format", dataFormat)
    }
    err:= hub.SendBatch(ctx, eventhubs.NewEventBatchIterator(eventsBatch...));

### Environment
- OS: mac/linux
- Go version: go version go1.14.2 darwin/amd64
- Version of Library: 
go mod

go 1.14

require (
	github.com/Azure/azure-event-hubs-go/v3 v3.2.0
	github.com/Azure/azure-kusto-go v0.1.3
	github.com/Azure/azure-sdk-for-go v42.3.0+incompatible // indirect
	github.com/Azure/go-amqp v0.12.7 // indirect
	github.com/Azure/go-autorest/autorest v0.10.1 // indirect
	github.com/Azure/go-autorest/autorest/adal v0.8.3 // indirect
	github.com/Azure/go-autorest/autorest/azure/auth v0.4.2
)

**Comment by kerend** [comment]
@rnitzan, please check EH metrics, and see if incoming and outgoing messages are as expected (10K).
Also please verify there is only one consumer per EH, per consumer group.
If issue still exists, please open a ticket to ADX with details of cluster name, connection name, and timeframe of occurence.

**Comment by rnitzan** [comment]
@kerend 

Reproduce every run for client  that send 10k outging events in batch 

WITHOUT the following 3 lines
_eventData.Set("Table", tableName)
eventData.Set("IngestionMappingReference", mappaingName)
eventData.Set("Format", dataFormat)__

**EH incoming 10k
EH outgoing 10k**


WITH those 3 lines set 

EH incoming 80k  EH outgoing 50k
outgoing is 50K cause i stopped the client

So this happen before ADX 

I opened azure ticket already for this issue

**Comment by rnitzan** [comment]
Closing due to not continue with this solution
Thanks
Raanan
