### ISSUE TITLE
Package fails to pull

### ISSUE THREAD

**Issue by kwontae** [Azure/azure-event-hubs-go#185]
### Expected Behavior
ADO build pipeline gets triggered to build docker image and
pulls the package without any complaints

### Actual Behavior
/home/vsts/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v3@v3.3.0/receiver.go:262:19: not enough arguments in call to msg.Modify
	have (bool, bool, nil)
	want (context.Context, bool, bool, amqp.Annotations)
/home/vsts/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v3@v3.3.0/receiver.go:269:18: not enough arguments in call to msg.Accept
	have ()
	want (context.Context)

### Environment
- OS: azure hosted vm
- Go version: 1.14.4
- Version of Library: 3.3.0

**Comment by kwontae** [comment]
this is causing our production build pipeline to fail please review

**Comment by devigned** [comment]
@jhendrixMSFT and @jjcollinge I believe this commit is causing some nasty side effect to upstream projects https://github.com/Azure/go-amqp/blame/8a245fd3417dda236aef063b29105d72c3ca14a6/types.go#L1826

Any chance to make the change in go-amqp backward compatible by introducing method signatures that are the same as the previous signatures, but pass in a `context.Background` into the new methods?

**Comment by jhendrixMSFT** [comment]
@kwontae are you not building in module-aware mode?  EH v3.3.0 uses go-amqp v0.12.6.  How did your build pull a different version?

**Comment by kwontae** [comment]
@devigned @jhendrixMSFT 

So here are some things that I've discovered.

We have an azure pipeline that utilizes the [Go Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/go?view=azure-devops). Because of how it was built for an older version of go, I have a several other steps to ensure this task will use go 1.13.0 

The issue was that regardless of the setting of GO111MODULE recommended by their official documentation, the `go get` command task will ignore the presence of go.mod/go.sum and run the whole update and install procedure. It will initially pull the `goamqp@v0.12.6` and then proceeded to pull `v0.13.1` causing this whole issue. 

Talking with @devigned, I think in the past, when `go-amqp` didn't have a breaking change release in the minor version semantic, therefore this worked well, which led me to believe, it is building in module-aware mode. My fault for not having a deeper dive into if the build pipeline is actually pulling the depenencies with the versions that I've declared in the go.mod file. I've made a change to the pipelines that were following the pattern of `install go version` -> `go get` -> `go build` of the GO task and now the pipeline works as expected.

**Comment by jhendrixMSFT** [comment]
Thanks for the explanation and digging in, glad you got it working.  I too have been burned by inadvertently not building in module-aware mode.

Normally we wouldn't release a breaking change in a minor update, however since go-amqp is still in preview I allowed this one as I felt it was an overall improvement in the API and the right thing to do (i.e. having a context parameter to control the lifetime of the IO operation).  Once we hit v1.0.0 any breaking change will bump the major version and semantic import versioning will completely isolate consumers from breaking changes.

Given this sounds like it's been resolved I'm going to close this issue.
