### ISSUE TITLE
Provided offset not always honored when creating receiver

### ISSUE THREAD

**Issue by princjef** [Azure/azure-event-hubs-go#188]
### Expected Behavior

When calling `hub.Receive()` with `eventhub.ReceiveWithStartingOffset(offset)` as an option, the receiver starts reading from the provided offset.

### Actual Behavior

If a receiver was previously created and closed within the same `eventhub.Hub` client for the same consumer group + partition, the next call to `hub.Receive()` will start from wherever that receiver stopped.

This seems to stem from the fact that when creating a new receiver, the options are applied first and then the last stored checkpoint is retrieved, which overrides the checkpoint provided in the option:

https://github.com/Azure/azure-event-hubs-go/blob/9898ba65784f054a43e4b18c84b5abe5fe8217b1/receiver.go#L146-L156

I'm not sure if this is intentional behavior, but it feels like a bug. Two reasonable fixes would either be to apply the options after fetching the stored checkpoint or have a check to not use the stored checkpoint if an option specified a checkpoint already.

### Environment
- OS: MacOS Catalina, Alpine Linux (in Docker)
- Go version: 1.15.0
- Version of Library: 3.3.0

**Comment by catalinaperalta** [comment]
Thanks for the feedback, looking into this and your proposed change.

**Comment by jhendrixMSFT** [comment]
Fixed in v3.3.1.
