### ISSUE TITLE
$Default consumer group used to retrieve the checkpoint regardless of the one set in the opts

### ISSUE THREAD

**Issue by stefano-bossi** [Azure/azure-event-hubs-go#210]
### Expected Behavior
If I set a consumer group on the Receive(), I expect it to be used to invoke the persister.

### Actual Behavior
Instead the persister, at the very first time it's invoked, it receives "@Default"

It seems a problem with the order in which the opts are applied to the receiver struct.

### Environment
Environment
OS: alpine:3.10.6
Go version: 1.16.2
Version of Library: v3.3.7

**Comment by catalinaperalta** [comment]
Hi, thanks for reaching out! Will take a look at what's happening here.
