### ISSUE TITLE
error on persister.Read is not propagated on the hub.Receive

### ISSUE THREAD

**Issue by stefano-bossi** [Azure/azure-event-hubs-go#212]
Expected Behavior
If the persister returns an error on the first Read call, I expect the error to be propagated out on the hub.Receive()

Actual Behavior
If the persister returns an error on the first Read(), the Checkpoint field on the receiver will be left on the default value. This will cause the next Write() call to overwrite the old persisted Checkpoint with that default value, causing the consumer to restart to consume from the beginning of the queue.

Environment
Environment
OS: alpine:3.10.6
Go version: 1.16.2
Version of Library: v3.3.7

**Comment by catalinaperalta** [comment]
Thanks for reaching out! Will investigate this.
