### ISSUE TITLE
Requesting asynchronous mode in v3

### ISSUE THREAD

**Issue by euchungmsft** [Azure/azure-event-hubs-go#220]
### Expected Behavior

Please consider to add a switch for sync/async mode in message transmissions with v3 just as v1 does

### Actual Behavior

With v3, it seems like it only works synchronously for message transmissions waiting for the acknowledgement from EH as message receipt. I believe this can be done asynchronously just as v1 does

### Environment
- OS: Ubuntu 16 but no dependency in OS-versions
- Go version: v3x
- Version of Library: Tested with 3.3.9 but looks the same at all v3

**Comparisons**

Latency comparison between v3 and v1
![image](https://user-images.githubusercontent.com/20915976/124212666-553b6f80-db2a-11eb-9fcc-6198a5a0d27f.png)

Behavioral comparison between v3 and v1
![image](https://user-images.githubusercontent.com/20915976/124211168-a433d580-db27-11eb-91eb-d4c465dc74e3.png)

-	In brief, it looks like v3 is synchronous and v1 is asynchronous. It seems like both works as it’s explained in https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide. 
-	All ‘RX(Session): Disposition’ in the red box comes with ‘Settled: true, State: Accepted’
-	‘TX: Attach’ in the blue box, ‘SenderSettleMode’ in v1 ‘unsettled’, v3 ‘mixed’. After that, in ‘RX(Session): Attach’, it seems like both simply follows this switch in ‘TX: Attach’. I wonder if this makes the difference between v1 and v3
-	In both amqp@v0.11.0 and go-amqp@v0.13.1, ‘SenderSettleMode’ is defined in ‘type link struct’ of client.go. But it seems like there’s no exposure of this switch to end-user APIs of azure-event-hubs-go. It’s the same at both of v1 and v3 but I guess default value is different
-	I see no message loss at Receiver, as long as it waits enough for all ‘RX(Session): Disposition’s to come
-	Both of v1, v3 provides no options to select sync/async

**Conclusion**
-	Apparently v1 looks much faster by **skipping** something but it does all required steps. It only **defers** the acknowledgement from EH by ‘RX(Session): Disposition’. But in user app perspective, v1 is much better in terms of latency and entire turn around time in the context
-	I believe ‘Send-and-forget’ is one of most important usecase of EH. In the architecture point of view, it can be done at somewhere else in front of EH in some of cases. But consider to add an option for this in azure-event-hubs-go, so that users can make choice

**Comment by jhendrixMSFT** [comment]
Per the comment [here](https://github.com/Azure/azure-event-hubs-go/pull/133#issuecomment-523171388), service bus and event hubs expect the sender to send messages as unsettled and the receiver to be in mode first.  While other, invalid, combinations might work, there is no guarantee as they will continue to do so in the future.  Seems unlikely that we can change this but will defer to @richardpark-msft for confirmation.

If callers want to fire-and-forget messages they can use goroutines to do so.

```go
go a.Hub.Send(ctx, eventhub.NewEventFromString(string(body)))
```

**Comment by richardpark-msft** [comment]
Just confirming that what @jhendrixMSFT mentions is the way that the other Event Hubs SDKs for JS and .Net do. If a caller wants to fire and forget they can simply store off and await the Task/Promise at a later time, or in bulk. So similar to what you have in Go.

**Comment by nudbeach** [comment]
@richardpark-msft  'store off and await the Task/Promise at a later time' this is a big help for us to move on, thanks for your feedback

**Comment by jhendrixMSFT** [comment]
Closing as using goroutines is how to make async work.
