### ISSUE TITLE
detecting ServerBusy error

### ISSUE THREAD

**Issue by euchungmsft** [Azure/azure-event-hubs-go#227]
### Expected Behavior

'ServerBusy error' is one of the most important exception required to handle for publisher clients. Could you please guide me how to detect it from Error interface ? It would be better if there's exception definitions like .NET
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-messaging-exceptions#serverbusyexception

For now, it seems like there's no other choice but detecting it from `Error()`, like this 
`err.Error() == "Server Busy"`

### Environment
- OS: Write here
- Go version: Write here
- Version of Library: Write here

**Comment by richardpark-msft** [comment]
Hi @euchungmsft,

Is your goal to check that it's a specific error or is it more just trying to figure out if you should retry? One thing that I'm working on is possibly adding a marker method, similar to this in azcore (https://github.com/Azure/azure-sdk-for-go/blob/dcc9108ed8db94db491f10a08535e0b27a1a3087/sdk/internal/errorinfo/errorinfo.go).

So then the process would be using `errors.As` to check if the marker method is present, which would indicate the returned error is retriable.

**Comment by euchungmsft** [comment]
Thanks @richardpark-msft . Let me test this soon and I'll get back to you if there's further issues
