### ISSUE TITLE
Support for OpenTelemetry

### ISSUE THREAD

**Issue by sgallizia** [Azure/azure-event-hubs-go#255]
Are there any plans to add the support for OpenTelemetry?
Or is there the possibility in some way to use OpenTelemetry in the current version?

Thank You

**Comment by atoulme** [comment]
I started working on a receiver with this library at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12786

**Comment by richardpark-msft** [comment]
@sgallizia, we rely on [github.com/devigned/tab](https://github.com/devigned/tab) for our tracing support in Event Hubs. Looks like they're only supporting opencensus and opentracing at the moment.
