### ISSUE TITLE
Connection reset by peer on attempt to GetRuntimeInformation

### ISSUE THREAD

**Issue by ddeep2007** [Azure/azure-event-hubs-go#41]
### Expected Behavior
A connection should be established with the following environment variables set. 
EVENTHUB_CONNECTION_STRING,
EVENTHUB_NAMESPACE
EVENTHUB_NAME

### Actual Behavior
When attempting to invoke hub.GetRuntimeInformation it returns the following error - read tcp 10.118.100.85:50582->104.42.97.95:5671: read: connection reset by peer

Current failing code - 
```go
        hub, err := eh.NewHubFromEnvironment()
	if err != nil {
		fmt.Println("Failed to create event hub-", err)
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3600*time.Second)
	defer cancel()

	handler := func(c context.Context, event *eh.Event) error {
		fmt.Println(*event)
		return nil
	}
	runtimeInfo, err := hub.GetRuntimeInformation(ctx) //FAILS HERE
	if err != nil {
		fmt.Println("Failed to get runtime information-", err) 
		return err
	}
```
One interesting piece of information found while debugging is that it looks like the token provider in the namespace is not being set correctly (see attached debug image). That said, this could be a complete red herring. 

### Environment
- OS: mac
- Go version: 1.10.2 darwin/amd64
- Version of Library: v 0.3.1
![screen shot 2018-06-18 at 4 48 35 pm](https://user-images.githubusercontent.com/40073617/41568008-173b781a-7318-11e8-95ab-32695a24358a.png)

**Comment by devigned** [comment]
@ddeep2007 it looks like you have sensitive information in your image. You might want to obfuscate it.

**Comment by ddeep2007** [comment]
@devigned Thanks for pointing that out. I have shared the image and obfuscated the sensitive information.

**Comment by devigned** [comment]
@ddeep2007 can you build your hub explicitly via: https://github.com/Azure/azure-event-hubs-go/blob/ab7925c86c2c3eeb40ffafa149820faca6d6bedc/hub.go#L89-L107

To build your token provider, you'd use:
```go
provider, sasErr := sas.NewTokenProvider(sas.TokenProviderWithEnvironmentVars())
```
This will help me narrow down the issue.

**Comment by ddeep2007** [comment]
@devigned - I was able to build the hub explicitly as you specified above and see the same issue. What information do you need from me to help root cause? Here is the modified code now
`	
        namespace := os.Getenv("EVENTHUB_NAMESPACE")
	name := os.Getenv("EVENTHUB_NAME")

	provider, err := sas.NewTokenProvider(sas.TokenProviderWithEnvironmentVars())
	if err != nil {
		fmt.Println("Failed to establish sas token provider -", err)
		return err
	}

	hub, err := eh.NewHub(namespace, name, provider)
	if err != nil {
		fmt.Println("Failed to establish connection to event hub -", err)
		return err
	}

	// hub, err := eh.NewHubFromEnvironment()
	// if err != nil {
	// 	fmt.Println("Failed to create event hub-", err)
	// 	return err
	// }
	ctx, cancel := context.WithTimeout(context.Background(), 3600*time.Second)
	defer cancel()

	handler := func(c context.Context, event *eh.Event) error {
		fmt.Println(*event)
		return nil
	}
	runtimeInfo, err := hub.GetRuntimeInformation(ctx)
	if err != nil {
		fmt.Println("Failed to get runtime information-", err)
		return err
	}
`

**Comment by devigned** [comment]
Hmm... There are tests for this functionality. That makes me question if you have network access to the Event Hub host on port 5671.

**Comment by ddeep2007** [comment]
Is there any way I can test that?

**Comment by devigned** [comment]
```
telnet {your-sb-namespace}.servicebus.windows.net 5671
``` 
If you need telnet, just 
```
brew install telnet
```

If you can connect, you should see something like:
```
$ telnet foo.servicebus.windows.net 5671
Trying 52.168.133.222...
Connected to ns-sb2-prod-bl3-012.cloudapp.net.
Escape character is '^]'.
```

**Comment by ddeep2007** [comment]
That worked fine:
`Trying 104.42.97.95...
Connected to ns-eh2-prod-by3-511.cloudapp.net.
Escape character is '^]'.`

**Comment by ddeep2007** [comment]
@devigned - seems like an issue with my companies VPN. When trying this from an external wifi network the code worked fine.

**Comment by devigned** [comment]
We are thinking about adding web socket support. Would this help you?

**Comment by devigned** [comment]
@ddeep2007 closing the issue since it sounds like you have determined it's VPN related.

**Comment by BalloonWen** [comment]
> @devigned - seems like an issue with my companies VPN. When trying this from an external wifi network the code worked fine.

Thanks for your hint, I had the exactly same issue and now figured it out.

**Comment by Lackshu** [comment]
One thing worth checking out is the firewall in your network being opened for port 5671. I expected Event Hub to always be on 443. It worked for me after the port was opened up. Validated the port using tcpdump after referring to the protocol handshake doco for Event Hub/Service Bus.

**Comment by BalloonWen** [comment]
> One thing worth checking out is the firewall in your network being opened for port 5671. I expected Event Hub to always be on 443. It worked for me after the port was opened up. Validated the port using tcpdump after referring to the protocol handshake doco for Event Hub/Service Bus.

In my case they are both opened, but sometimes company firewall has some special settings which are not predictable.
