### ISSUE TITLE
event.PartitionKey is nil

### ISSUE THREAD

**Issue by GoEddie** [Azure/azure-event-hubs-go#42]
### Expected Behavior

For the partition key to be included in the event

### Actual Behavior

The partition key is null, is there something else i need to do to get it filled in?

### Environment
- OS: win 10
- Go version: 1.9
- Version of Library: latest from go get

**Comment by devigned** [comment]
There is nothing you should have filled in. The partition key was not set when the event is received from the broker. This is a bug and I'll supply a fix shortly.

**Comment by devigned** [comment]
@GoEddie the fix has been applied. Please let me know if it solves your problem.

**Comment by GoEddie** [comment]
Thanks, it still isn’t working but I can’t see the partition header on the ampq packet - I’ll dig a bit deeper and try and get a network trace :)

**Comment by devigned** [comment]
The tests are passing for sending and receiving the partition key. Are you not seeing that behavior?

Perhaps, add a breaking test to a PR and I’ll see what’s broken.

**Comment by GoEddie** [comment]
I’m not seeing the partition key header on the annotations, I’ll get some more details and probably find out what I’m doing wrong :)

**Comment by devigned** [comment]
@GoEddie any updates? Anything I can do to help?

**Comment by GoEddie** [comment]
no don't worry please close it :)

**Comment by iMoses** [comment]
It's quite a shame you didn't post what worked for you...
Could really help me right now, i'n having the same problem

**Comment by GoEddie** [comment]
This fixed it, I just wasn’t testing it correctly “add partition key to the received event #43“
