### ISSUE TITLE
Inconsistent function call

### ISSUE THREAD

**Issue by kaushiksriram100** [Azure/azure-event-hubs-go#44]
### Expected Behavior
got get -u github.com/Azure/azure-event-hubs-go/... results in no error.

### Actual Behavior
Seeing an error in a function call (inconsistent number of arguments)
```
mbp-0:$ go get -u github.com/Azure/azure-event-hubs-go/...
# github.com/Azure/azure-event-hubs-go/internal/test
../../Azure/azure-event-hubs-go/internal/test/suite.go:177:34: not enough arguments in call to client.ListByNamespace
	have (context.Context, string, string)
	want (context.Context, string, string, *int32, *int32)
mbp-0:$
```

### Environment
- OS: Darwin (MAC OS)
- Go version: go version go1.10.3 darwin/amd64
- Version of Library:

**Comment by devigned** [comment]
[Looks like this came in during the latest major version increment](https://github.com/Azure/azure-sdk-for-go/pull/1937). vgo can't come fast enough :).

I'll update to v17 shortly. In the mean time, you can use the `dep` instructions on the readme, or you can check out the v16 tag.

**Comment by devigned** [comment]
The latest version in master has the dependency updated, so `go get -u ...` should work again.
