### ISSUE TITLE
Context Timeouts to stop receiver. 

### ISSUE THREAD

**Issue by kaushiksriram100** [Azure/azure-event-hubs-go#48]
### Expected Behavior
hub.Receiver Stops receiving messages after context timeout. 

Code:
``` 
ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	for _, partitionID := range partitions {
		hub.Receive(ctx, partitionID, handler, eventhub.ReceiveWithLatestOffset())
	}
cancel()
fmt.Println("listening...")
```
The above sample code is creating a receiver per partition and then the context (ctx) is cancelled (worst case context gets done after 10 sec). I am expecting the receiver to stop at that point.  Please correct if my understanding is wrong. Would be good if that can be documented.

I do realize that to stop the receiver I can call hub.Close(ctx). 

### Actual Behavior
hub.Receiver continues to receive messages after the context is cancelled. 

### Environment
- OS: Linux
- Go version: go version go1.10.3 darwin/amd64
- Version of Library: master branch

**Comment by devigned** [comment]
`hub.Receive` returns `*ListenerHandle, error` [see the go docs](https://godoc.org/github.com/Azure/azure-event-hubs-go#Hub.Receive). 

`ListenerHandle` has a `Close(ctx)`, `Done()` and `Err()` which can be used to deal with closing a receiver, checking if the receiver has closed and getting the last error on the receiver.

The context provided to `hub.Receive` is used to control how long you would like to wait before timing out the connection to the message broker. Upon connection / link setup, the ListnerHande is returned.

You can also call `hub.Close` to close the receiver, but that would close all of the receivers for that hub.

**Comment by devigned** [comment]
@kaushiksriram100 do you have any feedback based on my explanation above?

**Comment by kaushiksriram100** [comment]
Thanks for the details. Seems reasonable. 

I think the first para about *ListenerHandle, Done() and Err() can be documented in the docs. 

So if I have to start a worker to consume messages from all the available partitions, I start a receiver on each partition using a for loop and use the returned ListenerHandle to check of receiver errors. When you say - “getting the last error on the receiver”, is this the ctx.Err() itself? What about any other error in the receiver (may be some partition errors). I am new to event hub so not sure what are the possible errors for a receiver at partition level. 

Next about handling a event when receivers are spawned for each partition. Currently I have an Event Handler that i’ve synchronized and appends events from receivers to a generic batch and flushes them to output based on some batch size and updates the checkpoints using the Write interface(synchronized). The problem I am facing is how to determine when I should update the checkpoint for each partition. Updating after each message might be expensive processing, but updating per batch means there could be messages from all partitions. Do you recommend creating a batch per partition?

Thanks,
Sriram

**Comment by kaushiksriram100** [comment]
Thanks for the details. Seems reasonable. I think the first para about *ListenerHandle, Done() and Err() can be documented in the docs. Also the 2nd para. I now get why receiver doesn’t stop. 

So if I have to start a worker to consume messages from all the available partitions, I start a receiver on each partition using a for loop and use the returned ListenerHandle to check of receiver errors. When you say - “getting the last error on the receiver”, is this the ctx.Err() itself? What about any other error in the receiver (may be some partition errors). I am new to event hub so not sure what are the possible errors for a receiver at partition level. 

Next about handling a event when receivers are spawned for each partition. Currently I have an Event Handler that i’ve synchronized and appends events from receivers to a generic batch and flushes them to output based on some batch size and updates the checkpoints using the Write interface(synchronized). The problem I am facing is how to determine when I should update the checkpoint for each partition. Updating after each message might be expensive processing, but updating per batch means there could be messages from all partitions. Do you recommend creating a batch per partition? Thanks, Sriram

**Comment by devigned** [comment]
>So if I have to start a worker to consume messages from all the available partitions, I start a receiver on each partition using a for loop and use the returned ListenerHandle to check of receiver errors. 

You can do exactly that and spin up a receiver per partition. This is kind of painful for folks, so we created the Event Processor Host (EPH) in https://github.com/Azure/azure-event-hubs-go/blob/fbff7e5d87fa647a80ea5059107c7309ac391b6c/eph/eph_test.go#L81-L111. EPH will manage distributing partitions across a collection of processors. We use Azure Storage Blob leases to manage leader election for a given partition. Basically, with EPH, you just need to provide a number of workers, start EPH and let it balance load on it's own. With that said, there's a bunch of documentation and "ease of use" functions that need to be added to the `eph` and `storage` packages.

>When you say - “getting the last error on the receiver”, is this the ctx.Err() itself? What about any other error in the receiver (may be some partition errors). I am new to event hub so not sure what are the possible errors for a receiver at partition level.

Astute observation. In the case of last error, it could be the ctx.Err() itself, or the last error encountered on the link. In the case of an unexpected failure which the receiver could not recover from, I'd expect it would be the last error from the link. We do try to handle common error scenarios, so your links should be relatively resilient. See also: https://github.com/Azure/azure-event-hubs-go/blob/fbff7e5d87fa647a80ea5059107c7309ac391b6c/receiver.go#L397-L403.

>Next about handling a event when receivers are spawned for each partition. Currently I have an Event Handler that i’ve synchronized and appends events from receivers to a generic batch and flushes them to output based on some batch size and updates the checkpoints using the Write interface(synchronized). The problem I am facing is how to determine when I should update the checkpoint for each partition. Updating after each message might be expensive processing, but updating per batch means there could be messages from all partitions. Do you recommend creating a batch per partition?

Batching and checkpointing frequency is rather case dependent. The system you've built may be able to replay events more than once and end up with the same result (idempotent). If so, then having fewer checkpoints would likely increase throughput while leaving a larger window of event to replay if a failure occurs. Like you said, if you write a checkpoint after each event, then you'd probably have lower throughput, but less replay. You may want to test a few values to find your proper balance.

The default for EPH is to write the checkpoint out to an Azure Storage Blob once a second if an event has been processed by the partition. I wouldn't put too much weight into this example. I just wanted to give you an example of what we've defaulted EPH to use.

The most important aspect of using the service is to understand the promises Event Hubs makes. The service promises at least once delivery, meaning you will receive the event at least one time, but possibly multiple times. That doesn't mean the service is going to replicate your event, but rather you may process the same event more than once. If you build your system with that in mind, you will be successful regardless of the batching scheme your choose.

Please don't hesitate to open an issue or PR when you feel like something needs fixing. We are happy to help and want to make using Event Hubs fun for Gophers. Cheers!

**Comment by devigned** [comment]
I'm going to close this as an issue. If you would like me to change the interface, please reopen and propose the change.

**Comment by kaushiksriram100** [comment]
Sure, thanks! Thanks for your inputs. Really helpful. +1

**Comment by kaushiksriram100** [comment]
Sorry to resurrect this. One question -> in hub.Close(ctx), what is the ctx define? Time it would wait before closing the hub? If hub.Close(ctx) return immediately with nil, can I assume hubs have closed successfully?

**Comment by devigned** [comment]
Another great question which I should explain more in the docs.

The context passed into close provides a period of time to allow for graceful shutdown. This involves closing down of sender and receiver links which may have not completely finished sending and receiving.

If it returns immediately with nil, you can assume that everything closed down properly.

I wanted to provide a mechanism for a consumer to specify the amount of time they will wait before forcefully shutting down the connection.

**Comment by kaushiksriram100** [comment]
Got it. If graceful shutdown is not possible within the context time, I would assume it returns an err. 

Also, I am observing that receivers die silently after a hour or so. Right now I am ignore the returned *ListenerHandle and restarting the hub after some time. I'll try to check the Err() on the ListenerHandle to see if the receiver actually dies or something else.

**Comment by devigned** [comment]
It should return context expired.

The latest changes in `master` should be resilient to error conditions. Give the latest bits a try. If you are able to replicate receivers dying after an hour or so, please create an issue with the error and it'll be address immediately.
