### ISSUE TITLE
Compilation error due to latest release of Azue Storage Blob Go

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-event-hubs-go#68]
### Expected Behavior
I can clone and compile this project successfully.

### Actual Behavior
Since the latest release of Azure Storage Blob (0.3.0) the older versions of the SDK have been [removed](https://github.com/Azure/azure-storage-blob-go/releases/tag/0.3.0) but there are still references to it in this project i.e. credentials.go leading to compilation errors.

### Environment
- OS: Mac OS X 10.13.6
- Go version: go1.11.1 darwin/amd64
- Version of Library: Latest (1.0.0) but all are affected

**Comment by devigned** [comment]
Thank you for the heads up. We have a couple dependencies that are still stabilizing. Though, I think this should be the last breaking change we see out of the storage library.

If you run the makefile, which requires `dep`, the project should build. I know that expects more from the build chain than really should be required.

I'm working on moving the project over to Go modules. I think I should have the PR in shortly.

**Comment by elsesiy** [comment]
Thanks for the prompt response 👍  even using dep it's not building for me as the [lock](https://github.com/Azure/azure-event-hubs-go/blob/master/Gopkg.lock#L58) file references the very same dependency.

Let me know if I can assist here further.

**Comment by devigned** [comment]
Oh no! I’m sorry you are running into this.That shouldn’t happen.

I’ll get this fixed tonight (currently in the key note at HashiConf).

**Comment by devigned** [comment]
Thank you for your patience.

I've tagged `v1.0.1`, which should fix the issues you ran into with our Storage dependency. Please let me know if this resolves your issue.

**Comment by elsesiy** [comment]
@devigned Hi there, thanks for the quick response and the provided fix. Unfortunately, it doesn't work as there are still some compilation issues using go modules. Maybe I'm doing something wrong but this is build output using `go build`:

```
../../go/pkg/mod/github.com/!azure/azure-event-hubs-go@v1.0.1/storage/credential.go:33:2: unknown import path "github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2017-10-01/storage": cannot find module providing package github.com/Azure/azure-sdk-for-go/services/storage/mgmt/2017-10-01/storage
../../go/pkg/mod/github.com/!azure/azure-sdk-for-go@v21.3.0+incompatible/services/eventhub/mgmt/2017-04-01/eventhub/version.go:3:8: unknown import path "github.com/Azure/azure-sdk-for-go/version": cannot find module providing package github.com/Azure/azure-sdk-for-go/version
```

**Comment by devigned** [comment]
@marstr can you give this a quick run? Seems like it works on Travis.

**Comment by marstr** [comment]
I've never cloned this repository before. I ran the following commands:

``` bash
cd ~/code
git clone git@github.com:Azure/azure-event-hubs-go.git
cd azure-event-hubs-go.git
go mod verify
make
```
My environment:
- OS: Mac OS 10.14
- Go version: go1.11.1 darwin/amd64

Everything seemed to build for me.

**Comment by marstr** [comment]
I followed up with `go build ./...` and that also seems to work.

**Comment by devigned** [comment]
@elsesiy I would really like to get to the bottom of what's going on with your build. I did have a slightly complicated time getting go modules to cooperate at times, so it might be something there.

One thought... Try to run `go clean -modcache` and then run `go build all` from the repo clone directory outside of your go path. I'm just trying to limit the number of variables to get to the root of the problem.

Again, I'm sorry you are going through this, but @marstr and I are committed to helping you get it resolved.

**Comment by elsesiy** [comment]
@devigned @marstr Thanks so much for the support, `go clean -modcache` did the trick and my project finally builds again! Keep up the good work 👍
