### ISSUE TITLE
Documentation missing for ReceiveWithEpoch

### ISSUE THREAD

**Issue by arne-cl** [Azure/azure-event-hubs-go#72]
### Expected Behavior

I would expect to find the description of the function at the given URL.

// ReceiveWithEpoch configures the receiver to use an epoch -- see https://blogs.msdn.microsoft.com/gyan/2014/09/02/event-hubs-receiver-epoch/
func ReceiveWithEpoch(epoch int64) ReceiveOption {
   ...
}

### Actual Behavior

The URL no longer works and is also not available on archive.org.

### Environment
- OS: -
- Go version: -
- Version of Library: -

**Comment by devigned** [comment]
Thank you for alerting me to this. I suppose it was an aging link, so I shouldn't be too surprised it disappeared. It is a bit surprising it wasn't on archive.org. I swear it existed at some point :).

I'll provide a better explanation of it's functionality in the documentation.

**Comment by devigned** [comment]
@arne-cl what do you think about the following for the documentation blurb.

> Specifying an epoch, an integer greater than 0, for a receiver will cause any receiver with a lower epoch value to be disconnected from the message broker. If a receiver attempts to start with a lower epoch than the broker currently knows for a given partition, the broker will respond with an error on initiation of the receive request.

**Comment by arne-cl** [comment]
Hi David,
that seems to be a good explanation.

Kind regards,
Arne
