### ISSUE TITLE
SendBatch

### ISSUE THREAD

**Issue by fantyz** [Azure/azure-event-hubs-go#76]
Hi,

I'm planning to use `SendBatch` to send multiple events to an Event Hub. I assume that this have a maximum events per batch?

I've haven't been unable to find any information on this neither in the SDK itself or in the service documentation.

Can I put as many events I'd like into a single event batch?
And is this documented somewhere?

Thanks,
Kasper

**Comment by devigned** [comment]
> A single batch must not exceed the 256 KB limit of an event. Additionally, each message in the batch uses the same publisher identity. It is the responsibility of the sender to ensure that the batch does not exceed the maximum event size.

I haven’t looked at the code in a bit, but there should be an error in batch construction that provides an error if the batch size is exceeded. If that is not handled, then it’s a bug.

Since we are discussing this, how would you like the library to behave in this situation?

**Comment by fantyz** [comment]
It would be very convenient to have those limits documented as part of `Send` and `SendBatch`. That would have saved me a lot of googling. Especially when the Azure docs aren't super easy find specifics in either 😉 

Do you know if the 256 KB limit is for the `Data` part only or is it the whole AMQP message (I assume there's a bunch of serialization/headers/whatnot associated with the batch as well)?

I'm not sure what is meant by "publisher identity" - is it still possible to set the individual partition keys on the events when using a batch?

It sounds reasonable to have `Send` and `SendBatch` return an error if the size is exceeded (preferably one that can easily be identified easily to make it easy to deal with it differently from other errors it might return).

**Comment by devigned** [comment]
The size limit is for the entire message including headers. For forming batch messages, Event Hub expects an AMQP wrapper message with headers which appends each message of the batch as part of the body in encoded format.

I'll be sure to add that documentation and tests for batch size errors.

**Comment by devigned** [comment]
This is no longer needed as the batch iterator ensures that max message size is handled without the consumer needing to know.
