### ISSUE TITLE
Setting checkpoint SequenceNumbers in events?

### ISSUE THREAD

**Issue by fantyz** [Azure/azure-event-hubs-go#77]
I have a piece of code that needs to read from an Event Hub from fixed duration back in time up until right now and quit listening/return.

This is straightforward to write with `hub.GetParitionInformation` to provide the latest sequence number and `event.GetCheckpoint` on each event received to match the event sequence number with  to see if its done reading.

The problem then arise when I want to write unit  tests of this code. I can easily mock `Hub` but I'm not able to create events with the sequence numbers set?

Am I missing something or should I go about solving the problem differently? Any pointers as to how to write this would be appreciated.

**Comment by fantyz** [comment]
OK, so I missed that the SDK actually won't allow me to start receiving from a specific point in time.

It seems to be missing from the SDK though as this is supported via `amqp.annotation.x-opt-enqueued-time` (http://azure.github.io/amqpnetlite/articles/azure_eventhubs.html#filter)?

Is this something that could get added in a not too distant future? Otherwise, do you accept PRs?

**Comment by devigned** [comment]
We didn’t include enqueue time filter initially, but would be happy to add it or accept a PR. This would be an awesome opportunity for a contribution.

Per mocking the Hub, that’s something we’ve wanted to do, but would take some restructuring. 

The approach for testing that I’d take would be to prime a Hub with events, read all events from the Hub, select a known enqueue time which provides a known number of events, reread the Hub with the chosen enqueue filter, and verify the events received are the expected.

I’m out of office today, but would gladly review the PR if submitted. Otherwise, I’m happy to add the feature in the upcoming week.

**Comment by fantyz** [comment]
"Prime a Hub" as in actually setup a Hub in Azure and use that one? I would really like to avoid unit tests turning into integration tests and all the implications that follow in the case of our own code.

I've ended up writing a thin layer that can be mocked that converts `eventhub.Event` into my own 
```
type Event struct {
  Data []byte
  SequenceNumber int64
}
```
It's annoying, but it makes the untestable part as small possible. It would be really nice to get rid of that again by allowing me to somehow create mocked eventhub.Event with values for the `Checkpoint` set as well.

Regarding the PR; I'll take a look over the weekend.

**Comment by fantyz** [comment]
A summary of trying to write unit tests of my code that relies on a `Hub` for receiving data:
- The events that have a mix of access-by-public-field (ie. `Data`) and methods accessing private fields (ie. `GetCheckpoint()`). It would be testable if it was consistently in one way or the other. If the fields are public, I would be able to make fake events. If it relied entirely on methods I would specify an event interface and I would be able to write mock events for testing purposes.
- Receive returns a handle that I cannot mock due to it in turn relying on `*receiver` which is private and not settable - if I make a fake ListenerHandle then `Close(...)` will cause it to panic.

This means I cannot create a mock that includes `Receive` 😒 

This is stuff that is hard to change/fix without breaking backwards compatibility in the SDK.

Do you have any suggestions as to how I should proceed?

**Comment by devigned** [comment]
I see your point. Mocking these structures is difficult if not impossible. We tried to keep the public interface as thin as possible, but it has a cost.

Would you author a test as you would like it to work? 

Let me think about this as these would likely be breaking changes (as you said) and I'd like to avoid that if possible.

As a side note, have you seen the interface for Receive in Azure Service Bus for Go (https://github.com/Azure/azure-service-bus-go/blob/5c0fda85553833c58a1ba9c087440ec340511d34/queue.go#L343-L355). We moved away from the close handle and made all of the functions synchronous. What do you think about this pattern vs. the close handle?

**Comment by devigned** [comment]
@fantyz I'm going to close this issue since I think the checkpointing / sequence number / point in time issue is fixed, and I've move the discussion of the an improved testing experience into a new issue marked for `v2.0`. If you feel like this issue should not be close, please reopen it.
