### ISSUE TITLE
 Missing configuration param for checkpointing frequency

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-event-hubs-go#79]
### Expected Behavior
As a user, I want to be able to set the frequency of checkpoints being written to the Azure Blob storage. I'm using an EPH for managing the partitions at scale.

### Actual Behavior
The `handleMessage` method emits a checkpoint update on every single message. I'm in a high volume environment (> 100 messages/day) which noticeably slows down the possible throughput.

### Environment
- OS: `Mac OS X 10.14.1`
- Go version: `go1.11.2 darwin/amd64`
- Version of Library: `v1.0.1`

**Comment by devigned** [comment]
When `handleMessage` emits a checkpoint, the storage checkpointer accepts the checkpoint, but doesn't synchronously persist it.

https://github.com/Azure/azure-event-hubs-go/blob/a7f5b65899dd97e6ed075201a3a67b80ce229310/storage/storage.go#L408-L428

The storage checkpointer has a go routine which periodically persists the checkpoints.

https://github.com/Azure/azure-event-hubs-go/blob/a7f5b65899dd97e6ed075201a3a67b80ce229310/storage/storage.go#L113-L118

https://github.com/Azure/azure-event-hubs-go/blob/a7f5b65899dd97e6ed075201a3a67b80ce229310/storage/storage.go#L466-L516

Would making the periodic persistence configurable help you out? Are you using the Azure Storage checkpointer?

**Comment by elsesiy** [comment]
Thanks for the quick reply 👍 
Yes making the periodic persistence configurable is exactly what I'm asking for. The frequency is too high for us, so I'd love to set it to like 10s or so.

**Comment by devigned** [comment]
Happy to help! I’ll probably be able to get in over the next couple days. 

Please don’t hesitate to bring up other improvements. Thank you.

**Comment by elsesiy** [comment]
Will you create a release right away? :)

**Comment by devigned** [comment]
I'm on it :)

**Comment by devigned** [comment]
tagged `v1.1.0`. Please don't hesitate to bring up other ideas for improving the experience.
