### ISSUE TITLE
Expired credentials

### ISSUE THREAD

**Issue by fantyz** [Azure/azure-event-hubs-go#81]
Hi,

We're having issues with sending events to event hub. This particular sender sends events once a day. First time it runs, it works fine. 24 hour later we consistently get the error:  `link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'x.servicebus.windows.net/manifests'., Info: map[]}`.

Any idea why this is happening and whether we're missing something or its a bug in the SDK?

We setup event hubs as follows:
```
// Setup SAS token based provider for EventHub client
tpo := sas.TokenProviderWithKey(c.Azure.EventHubs.KeyName, c.Azure.EventHubs.KeyValue)
tp, err := sas.NewTokenProvider(tpo)
if err != nil {
	log.Error(errors.Wrapf(err, "Unable to create SAS token provider for EventHub"))
	os.Exit(1)
}

// setup the EventHub client using the SAS token provider
eventHubClient, err := eventhub.NewHub(c.Azure.EventHubs.Namespace, c.Azure.EventHubs.ManifestsEventHub, tp)
if err != nil {
	log.Error(errors.Wrapf(err, "Unable to create EventHub client"))
	os.Exit(1)
}
```

### Environment
- OS: Docker scratch
- Go version: `1.11.1`
- Version of Library: `v0.4.0 (fbff7e5d87fa647a80ea5059107c7309ac391b6c)`

**Comment by devigned** [comment]
Is `v0.4.0` an accurate version? If so, I would suggest updating to 1.0 or greater. There was a fair amount of stability / performance work done between `v0.4.0` and `v1.0.0` (https://github.com/Azure/azure-event-hubs-go/compare/v0.4.0...master).

**Comment by fantyz** [comment]
Sadly updating to `v1.0.0` did not fix the issue

**Comment by devigned** [comment]
> Any idea why this is happening and whether we're missing something or its a bug in the SDK?
You are setting up the Hub and token provider as you should be. I don't see anything wrong with your code.

This sounds like a bug, and one I would very much like to correct with your assistance.

Here's a little background. With SAS token provider, a token is generated from KeyName and KeyValue with a 2 hour lifespan. That token is used to negotiate claims-based auth for the AMQP connection, session, link. I would expect the link to be detached by the server over a long period of time either through inactivity or expired claims. This in itself is not a big deal as the library should expect such detaches and do its best to recover from those. When the sender runs into an error, such as a detach, it will kill the link, session and connection, rebuild them, and in the process of rebuilding them, generate a new token & renegotiate claims. 

We actually tested for this scenario for the 1.0 release, so I'm really surprised the error is not recovered when your app attempts to send via `trySend` since the error you specified should be a `*amqp.DetachError`.
https://github.com/Azure/azure-event-hubs-go/blob/a7f5b65899dd97e6ed075201a3a67b80ce229310/sender.go#L125-L163

Any chance you could collect OpenCensus traces or other information to help determine the root of this issue?

I'm going to replicate your scenario in our test infrastructure and try to reproduce the error.

A work around for this in the mean time would be to create a new Hub instance each 24 hours.

**Comment by AndreasHaure** [comment]
Hi @devigned

We have now set up export of OpenCencus tracing for our application. The image below shows a Flame Graph for the successful case which occurs the first time a message is sent to the event hub which happens only the first time our application is executed:

![success1](https://user-images.githubusercontent.com/3206723/50157258-445ee180-02d1-11e9-8499-8009b890c22f.png)

Here is an image zoomed in on what happens under the `az_amqp_common.rpc.Close` span:
![success2](https://user-images.githubusercontent.com/3206723/50155213-c64c0c00-02cb-11e9-87f1-568d179fa272.png)

Here is the logged Span metadata corresponding to the trace:
```
eh.Hub.Send - METADATA
{
component: github.com/Azure/azure-event-hubs-go
peer {
hostname: app
}
version: 1.1.0
}

eh.Hub.getSender - METADATA
{
component: github.com/Azure/azure-event-hubs-go
peer {
hostname: app
}
version: 1.1.0
}

eh.sender.Send - METADATA
{
component: github.com/Azure/azure-event-hubs-go
message_bus {
destination: amqps://EVENTHUB_NAMESPACE.servicebus.windows.net/EVENTHUB_NAME
}
peer {
hostname: app
}
span {
kind: producer
}
version: 1.1.0
}

eh.Sender.newSender - METADATA
{
component: github.com/Azure/azure-event-hubs-go
event: creating a new sender for entity path manifests
level: debug
peer {
hostname: app
}
version: 1.1.0
}

eh.sender.trySend - METADATA
{
component: github.com/Azure/azure-event-hubs-go
he {
message_id: 8bb017f5-15b2-4f3e-ac49-f557b745902f
}
message_bus {
destination: amqps://EVENTHUB_NAMESPACE.servicebus.windows.net/EVENTHUB_NAME
}
peer {
hostname: app
}
span {
kind: producer
}
version: 1.1.0
}

eh.sender.newSessionAndLink - METADATA
{
component: github.com/Azure/azure-event-hubs-go
message_bus {
destination: amqps://EVENTHUB_NAMESPACE.servicebus.windows.net/EVENTHUB_NAME
}
peer {
hostname: app
}
span {
kind: producer
}
version: 1.1.0
}

eh.namespace.negotiateClaim - METADATA
{
component: github.com/Azure/azure-event-hubs-go
peer {
hostname: app
}
version: 1.1.0
}

az_amqp_common.cbs.NegotiateClaim - METADATA
{
component: github.com/Azure/azure-amqp-common-go
event: negotiated with response code 202 and message: Accepted
level: debug
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.RetryableRPC - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.Close - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.RetryableRPC.retry - METADATA
{
component: github.com/Azure/azure-amqp-common-go
event: successful rpc on link 3743d06c-448c-49ec-b3c5-7c0757fa12af: status code 202 and description: Accepted
level: debug
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.closeReceiver - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.closeSender - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.closeSession - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}

az_amqp_common.rpc.RPC - METADATA
{
component: github.com/Azure/azure-amqp-common-go
peer {
hostname: app
}
version: 1.0.1
}
```

After 24 hours the job is executed again and this time we get the error that @fantyz mentions. Below is the Flame Graph for all successive runs (Job is executed every 24 hours):
![failed](https://user-images.githubusercontent.com/3206723/50156993-89cedf00-02d0-11e9-8a65-ceca83f0b81a.png)

This time it appears that no renegotiation of the token takes place and there are no traces from the `amqp` package. 

Here is the logged Span metadata corresponding to the trace:
```
eh.Hub.Send - METADATA
{
component: github.com/Azure/azure-event-hubs-go
peer {
hostname: app
}
version: 1.1.0
}

eh.Hub.getSender - METADATA
{
component: github.com/Azure/azure-event-hubs-go
peer {
hostname: app
}
version: 1.1.0
}

eh.sender.Send - METADATA
{
component: github.com/Azure/azure-event-hubs-go
message_bus {
destination: amqps://EVENTHUB_NAMESPACE.servicebus.windows.net/EVENTHUB_NAME
}
peer {
hostname: app
}
span {
kind: producer
}
version: 1.1.0
}

eh.sender.trySend - METADATA
{
component: github.com/Azure/azure-event-hubs-go
he {
message_id: 7933c470-ace2-4d94-a3a5-ec8d8a924325
}
message_bus {
destination: amqps://EVENTHUB_NAMESPACE.servicebus.windows.net/EVENTHUB_NAME
}
peer {
hostname: app
}
span {
kind: producer
}
version: 1.1.0
}
```

Maybe I should add that for each invocation of `Send` we pass in a new context with a timeout of 30 seconds.

Please let me know in case you need more information.

**Comment by AndreasHaure** [comment]
Thanks for the quick reply.

The context with a timeout of 30 seconds is defined right before the `send` invocation. And a new context with said deadline is passed in for each invocation of `send`. Only a single message is sent every 24 hours and the payload every time is only about 4kb. So I guess it should not able able to reach a timeout.

Unfortunately I don't see any errors in the log statements for any of the traces.

I can see that our `go-autorest` version is somewhat outdated from the newest v.11.2.8. Any chance that this could have an influence? I will try to upgrade it and see if that changes anything.

**Comment by vcabbage** [comment]
You may want to double check the version of https//github.com/vcabbage/amqp (pack.ag/amqp) you're pulling in. An earlier version of the lib returned `DetachError` instead of `*DetachError`, that would cause the type switch @devigned referenced above to hit the default case and the link would not be recovered.

**Comment by devigned** [comment]
`go-autorest` shouldn't have any impact in this code path.

Good idea, @vcabbage! I hadn't thought about that. It certainly could exhibit this kind of behavior.

I would expect near instant sends for a 4 kb message. Though, if the CBS needs to be negotiated, that would add a bit of time, but nothing close to 30 seconds.

**Comment by AndreasHaure** [comment]
@vcabbage Thanks for the tip! It looks like we were using v0.4.0 of `pack.ag/amqp`, so I will try upgrading it and let you know if that solves the issue.

**Comment by fantyz** [comment]
It looks like updating `pack.ag/amqp` has fixed the issue. @AndreasHaure was able to reproduce the error while having it running on a 3 hour loop. He did the update yesterday and it has been running without issue ever since.

Lesson learned: Dependencies of dependencies doesn't manage themselves.

Thanks a lot for the help @vcabbage and @devigned!

**Comment by devigned** [comment]
@fantyz quick question, are you using go modules for dependencies?

**Comment by fantyz** [comment]
Nope, it's still experimental. Waiting for it to become official in v1.12 before switching.

**Comment by devigned** [comment]
Understandable. When you do adopt go modules, this should not happen any more.

Seems like this issue can be closed. If you disagree, please reopen.

Thank you for the help, @vcabbage!
