### ISSUE TITLE
TCP connections stay open when sending

### ISSUE THREAD

**Issue by tomconte** [Azure/azure-event-hubs-go#86]
### Expected Behavior

I have a piece of code that sends data by calling NewHubFromConnectionString(), SendBatch() and finally Close() on the Hub. The functions is called multiple times in a loop. After leaving the code running for a while I can see many connections left open to the Event Hub endpoint, and they keep piling up.

### Actual Behavior

I was assuming that when calling Hub.Close() the connection to EH would be closed.

Should Hub.Close() also call Close() on the sender? e.g. in https://github.com/Azure/azure-event-hubs-go/blob/master/hub.go#L521

### Environment

- OS: Linux or Mac
- Go version: go version go1.11.2 darwin/amd64
- Version of Library: 1.0.1

**Comment by devigned** [comment]
Yes it should. I'll put out a patch shortly.
