### ISSUE TITLE
Event processor host: status description was not found on rpc message

### ISSUE THREAD

**Issue by JuustoMestari** [Azure/azure-event-hubs-go#88]
### Expected Behavior
No error when creating a new event hub processor

### Actual Behavior
Error when creating eventhub processor :  **status description was not found on rpc message**

### Environment
- OS: Docker image built in golang:alpine
- Go version: 1.11.1
- Version of Library: not sure, just used **go get**

I was using the code from the example for the eventhub processor (https://github.com/Azure/azure-event-hubs-go#event-processor-host) and it was working fine for a while (about a few weeks) but now when running **processor, err := eph.New(ctx, parsed.Namespace, parsed.HubName, provider, leaserCheckpointer, leaserCheckpointer)** I get the error message "status description was not found on rpc message"
Any idea what might cause this issue?

**Comment by krpranay** [comment]
Hi,

Even I am getting same error during eph.new call. Can you guys suggest if this is any new bug introduced or need any addition setting.

**Comment by devigned** [comment]
What version of `github.com/Azure/azure-amqp-common-go` are you running, @JuustoMestari and @krpranay? Are you using go modules, or `go get` without module support?

The error is happening due to an RPC request not finding the status description on a RPC response (https://github.com/Azure/azure-amqp-common-go/blob/12877250384ded92c1b1a2affe969579aaef97d4/rpc/rpc.go#L210). This is most definitely a bug. I'm surprised it's not showing up in our integration tests.

**Comment by devigned** [comment]
To add to the path of execution leading to this error.
``` go
eph.New --> Hub.GetRuntimeInformation // to determine how many partitions the Hub has
Hub.GetRuntimeInformation --> client.GetHubRuntimeInformation // which makes an AMQP RPC call to the EH mgmt interface
client.GetHubRuntimeInformation --> github.com/Azure/azure-amqp-common-go/rpc/Link.RetryableRPC // to make the RPC call w/ retry
Link.RetryableRPC --> Link.RPC // to make the RPC call
Link.RPC // tries to decode the response and finds no status description
```

**Comment by JuustoMestari** [comment]
I just used **go get github.com/Azure/azure-amqp-common-go**  on a fresh install and I got the error so I guess it's the latest version? I am not sure how to check the exact version of a go package?

**Comment by devigned** [comment]
@JuustoMestari if you are running `go get` without module support, then you are getting `head` from the repo. If you use go modules, you would then be able to lock down the version in your project's `go.mod` file like we do here https://github.com/Azure/azure-event-hubs-go/blob/master/go.mod.

That aside, I'm going to change the status description to be optional on RPC. I don't believe it is needed and that we were being overly harsh in the parsing of RPC responses. With that said, I just ran the tests for Hub mgmt and everything seems fine. I wonder what exactly you are seeing as a response from the server and why it differs from what I'm seeing.

Would you be able to add a `fmt.Printf` statement to https://github.com/Azure/azure-amqp-common-go/blob/1b596336a6a312412941a90cfa65716072de9cb7/rpc/rpc.go#L173 to show everything in the `res.ApplicationProperties` map? It would be super helpful.

**Comment by JuustoMestari** [comment]
@devigned Here is the content of **res.ApplicationProperties** , hope this helps :
`map[operation:READ status-code:200]`

**Comment by devigned** [comment]
That helps greatly! The good news is that the request is successful. Bad news is that it doesn't have a status description. I'm guessing that is a change in the server side code which has not been rolled out to all environments.

I'll change the parsing logic to be more permissive. The change should be available shortly. Thank you for your help!

**Comment by devigned** [comment]
@JuustoMestari, I've merged the fix. Would you run `go get -u ...` and let me know if this resolves the issue?

**Comment by krpranay** [comment]
@devigned I just took latest and it works like charm. Thanks for quick fix.

**Comment by devigned** [comment]
Awesomesauce! I'll release an update module dependency for the EH module.

Thank you again!
