### ISSUE TITLE
GetRuntimeInformation not working

### ISSUE THREAD

**Issue by fantyz** [Azure/azure-event-hubs-go#90]
We have started seeing an issue that seems to be unrelated to any changes done in our end.

`GetRuntimeInformation` has begun returning the error `status description was not found on rpc message` which is causing a crash as it use the runtime information to discover partitions.

Any advice on how to fix this would be much appreciated.

### Environment
- Go version: `1.11.4`
- Version of Library:
```
[[constraint]]
  name = "github.com/Azure/azure-amqp-common-go"
  version = "1.1.3"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "1.1.1"
```

**Comment by fantyz** [comment]
Seems to be directly related to #88. We'll do an update of versions and see if that fixes it.

**Comment by fantyz** [comment]
Updating to amqp to 1.1.4 and the sdk to 1.1.2 resolved the issue.

Breaking changes like that aren't cool!

**Comment by devigned** [comment]
Glad that fixed the issue!
