### ISSUE TITLE
Goroutine Leak in azure-event-hubs-go/storage.(*LeaserCheckpointer).persistDirtyPartitions

### ISSUE THREAD

**Issue by traviswt** [Azure/azure-event-hubs-go#92]
### Expected Behavior
Event consumption and processing with consistent amount of goroutines increasing and decreasing as necessary to accomplish function.

### Actual Behavior
Continual increase in goroutines until the process runs out of resources and becomes un-responsive while using the Event Processor Host and the included LeaseCheckpointer while events are being consumed on a consistent basis.

#### Analysis
From my analysis it appears there is goroutine leak in the storage package(azure-eventhubs-go/storage.go:493). The function persistDirtyPartitions creates a channel and sends to a channel that has receipt in the next for loop, this set of actions is leaking a send almost every lease and persist interval as events are flowing through.

I've reproduced the issue using the example code from this repo's readme and adding a goroutine count loop and an endpoint to dump a stack. The example receiver code is below. Run the receiver, and send events through an Event Hub with Multiple Partitions for a few minutes and then look at the stack, you can see that there are many leaked chan send go routines on the persistDirtyPartitions function.

#### Potential Fix
I've changed the storage.go code to something simpler and it seems to resolve the issue, i may not understand why the more complex channel version was there, so take it as a reference.
```
func (sl *LeaserCheckpointer) persistDirtyPartitions(ctx context.Context) error {
	sl.leasesMu.Lock()
	defer sl.leasesMu.Unlock()

	span, ctx := startConsumerSpanFromContext(ctx, "storage.LeaserCheckpointer.persistDirtyPartitions")
	defer span.End()

	// resCh := make(chan dirtyResult)
	// for partitionID := range sl.dirtyPartitions {
	// 	go func(id string) {
	// 		err := sl.persistLease(ctx, id)
	// 		resCh <- dirtyResult{
	// 			Err:         err,
	// 			PartitionID: id,
	// 		}
	// 	}(partitionID)
	// }

	// var lastErr error
	// for i := 0; i < len(sl.dirtyPartitions); i++ {
	// 	select {
	// 	case <-ctx.Done():
	// 		return ctx.Err()
	// 	case res := <-resCh:
	// 		if res.Err != nil {
	// 			lastErr = res.Err
	// 		}
	// 		delete(sl.dirtyPartitions, res.PartitionID)
	// 	}
	// }
	// return lastErr

	ptd := make(map[string]string)
	var lastErr error
	for partitionID := range sl.dirtyPartitions {
		go func(id string) {
			err := sl.persistLease(ctx, id)
			if err != nil {
				lastErr = err
			}
			ptd[id] = id
		}(partitionID)
	}

	for pID := range ptd {
		delete(sl.dirtyPartitions, pID)
	}

	return lastErr
}
```

### Environment
- OS: ```macOS Mojave 10.14.2```
- Go version: ```1.11.2```
- Version of Library: ```v1.1.2```

### Example Receive Code
```
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"runtime"
	"runtime/debug"
	"runtime/pprof"
	"time"

	"github.com/Azure/azure-amqp-common-go/conn"
	"github.com/Azure/azure-amqp-common-go/sas"
	eventhub "github.com/Azure/azure-event-hubs-go"
	"github.com/Azure/azure-event-hubs-go/eph"
	"github.com/Azure/azure-event-hubs-go/storage"
	"github.com/Azure/azure-storage-blob-go/azblob"
	"github.com/Azure/go-autorest/autorest/azure"
	log "github.com/sirupsen/logrus"
)

func main() {

	mux := http.NewServeMux()
	mux.HandleFunc("/_stack", getStackTraceHandler)

	httpServerClosedChan := make(chan struct{})
	go func() {
		log.Infof(
			"Listening for HTTP requests at: %v\n",
			"http://localhost:8080",
		)
		httpErr := http.ListenAndServe(":8080", mux)
		if httpErr != nil && httpErr != http.ErrServerClosed {
			log.Errorf("HTTP Server error: %v\n", httpErr)
		}
		close(httpServerClosedChan)
	}()

	// Azure Storage account information
	storageAccountName := ""
	storageAccountKey := ""
	// Azure Storage container to store leases and checkpoints
	storageContainerName := ""

	// Azure Event Hub connection string
	eventHubConnStr := ""
	parsed, err := conn.ParsedConnectionFromStr(eventHubConnStr)
	if err != nil {
		// handle error
	}

	// create a new Azure Storage Leaser / Checkpointer
	cred, err := azblob.NewSharedKeyCredential(storageAccountName, storageAccountKey)
	leaserCheckpointer, err := storage.NewStorageLeaserCheckpointer(cred, storageAccountName, storageContainerName, azure.PublicCloud)
	if err != nil {
		// handle error
	}

	// SAS token provider for Azure Event Hubs
	provider, err := sas.NewTokenProvider(sas.TokenProviderWithKey(parsed.KeyName, parsed.Key))
	if err != nil {
		// handle error
	}

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	// create a new EPH processor
	processor, err := eph.New(ctx, parsed.Namespace, parsed.HubName, provider, leaserCheckpointer, leaserCheckpointer)
	if err != nil {
		// handle error
	}

	// register a message handler -- many can be registered
	handlerId, err := processor.RegisterHandler(ctx,
		func(c context.Context, event *eventhub.Event) error {
			fmt.Println(string(event.Data))
			return nil
		})
	if err != nil {
		// handle error
	}

	go func() {
		for {
			select {
			default:
				numGr := runtime.NumGoroutine()
				log.Infof("goroutine count: %v\n", numGr)
				<-time.After(5 * time.Second)
			}
		}
	}()

	// start handling messages from all of the partitions balancing across multiple consumers
	processor.StartNonBlocking(ctx)

	log.Infof("Receiving events from eventhub: %v %v handlerId: %v\n", parsed.Namespace, parsed.HubName, handlerId)

	// Wait for a signal to quit:
	signalChan := make(chan os.Signal, 1)
	signal.Notify(signalChan, os.Interrupt, os.Kill)
	<-signalChan

	processor.UnregisterHandler(ctx, handlerId)

	err = processor.Close(context.Background())
	if err != nil {
		// handle error
	}
}

func getStackTraceHandler(w http.ResponseWriter, r *http.Request) {
	stack := debug.Stack()
	w.Write(stack)
	pprof.Lookup("goroutine").WriteTo(w, 2)
}
```

**Comment by traviswt** [comment]
Could I get a status update on this issue? We can't use this library for now since it has this leak.

**Comment by devigned** [comment]
I've been focused on another project. I'll fix this by the end of the week. Thx for the nudge.

**Comment by devigned** [comment]
I've run out of time this evening. I'll update tomorrow.

**Comment by devigned** [comment]
@traviswt do you want to give the PR for the fix a test run?

The current build is failing due to some internal test infrastructure. It's in process of being sorted out. If the fix works for you and when the test infrastructure get's back to normal, we'll get the PR merged.

**Comment by devigned** [comment]
@traviswt if you are wondering why I didn't use the solution you suggested it's that the function will complete before all of the concurrent persists are completed. At that point, the persistDirtyPartitions func will be rescheduled. There's a chance the func would be invoked twice at the same time. The mutex guard will protect from the two instances running at the same time, but it will end up in timing that is unintended. The timing I was going for is that the func will not be rescheduled until the previous invocation has completed.

**Comment by traviswt** [comment]
Sorry for the delay. I'll test the fix tonight, thanks for getting the change put in! The solution I put in the issue was just something simple I was using to see if I could reproduce or not I figured there was something more advanced going on that I didn't spot looking at the code!

**Comment by traviswt** [comment]
I verified the fix works as expected, there is not a leak anymore! Thanks for getting this fixed!
