### ISSUE TITLE
File persister being overwritten by receiver options

### ISSUE THREAD

**Issue by R290** [Azure/azure-event-hubs-go#95]
### Configuration

- Eventhub configured with offset persistence using `persist.FilePersister` 
- Receiver(s) configured with `ReceiveFromTimestamp`
- Static configuration (the configuration does not change between runs)

### Expected Behavior

The offset saved in the `FilePersister` directory of the hub optionally supersedes the offset given as receiver option.

### Actual Behavior

On receiver creation the offset in the `FilePersister` directory is immediately overwritten with the one from the receiver option (e.g. https://github.com/Azure/azure-event-hubs-go/blob/master/receiver.go#L104). As a consequence events are received multiple times if the application is restarted.

I can understand if this is by design and cannot be changed, in that case I'll create a workaround for my specific implementation. Ideally a setting could be created to which offset has preference, either specific for the file persister or for all persisters. 

### Environment
- OS: `Fedora 29`
- Go version: `go version go1.11.5 linux/amd64`
- Version of Library: `head` (commit b14f5f2a2500e9ecdb3d3e3332e2c0fabd9da5b6)

**Comment by devigned** [comment]
The functionality here should be that the receiver would use the file's checkpoint and start from there, rather than starting over from the beginning. I believe this to be a bug.

Thank you for reporting this. I'll try to get to it in upcoming week. If you need it sooner, please feel free to submit a PR.

**Comment by duydao** [comment]
This bug seems to limit the possibility for an integration of event hub into telegraf.

@R290 Is there any chance you could submit a PR with a bugfix?

 We're very interested to use event hubs in combination with telegraf.
