### ISSUE TITLE
Using event-hub go library to connect to an iot hub

### ISSUE THREAD

**Issue by talmdal** [Azure/azure-event-hubs-go#96]
### Expected Behavior
Not sure if this is possible. @devigned mentioned on another repository, that it might be possible to connect to an IoT Hub using this library.  If this is indeed possible, I would expect to be able to create a connection to the hub by providing a connection string in the format:
`HostName=hubname.azure-devices.net;DeviceId=deviceID;SharedAccessKey=...`

### Actual Behavior
When  I attempt to connect I get a message that says "key "Endpoint" must not be empty"

Am I trying to do something that wasn't designed for?

### Environment
* OS: `MacOS v10.13.6`
* Go version: `go version go1.11.2 darwin/amd64`
* Version of Library: V1.1.2

**Comment by devigned** [comment]
I see the issue. The connection string is in a different format than what is expected for Event Hubs. I will add a constructor to parse this and construct a Hub or a EventProcessorHost.

As for the message, that is due to the connection string for Event Hub requiring `Endpoint` as one of the keys. As you can see in the IoT connection string, it's actually `HostName`.

**Comment by devigned** [comment]
As a side note, I did give this a try today, and I believe I will also need to handle a redirect upon connection to the uri in the IoT connection string.

**Comment by devigned** [comment]
related to: https://github.com/vcabbage/amqp/issues/153

**Comment by talmdal** [comment]
Thanks for that, I appreciate you looking in to it

**Comment by devigned** [comment]
Man, @talmdal. Thank you for taking the time to write up an issue and try out our stuff. You are 👍

**Comment by talmdal** [comment]
@devigned, I was thinking and I appreciate what you are doing, but I'm concerned that we might be trying to make the event-hub library more than it was meant to be.  If I understand correctly, it is meant to allow applications to connect to event hub for event in-gestation and extraction in go programs.  it's very specific in that the code is looking for partitions to access.

If I'm correct in my understanding, then I'm concerned that the trying to "shoe-horn" the IoT hub messaging and functionality into this project may increase it's complexity.  As an example, parsing the connection string based on the approach in the amqp-common project looks similiar to this:

``` go
// ParseConnectionString parses the given string into a Credentials struct.
// If you use a shared access policy DeviceId is needed to be added manually.
func parseConnectionString(cs string) (IotHubConnectionDefinition, error) {
  if cs == "" {
    return nil, errors.New("please provide a valid connection string")
  }

  chunks := strings.Split(cs, ";")

  m := &iotHubConnectionString{}
  for _, chunk := range chunks {
    c := strings.SplitN(chunk, "=", 2)
    if len(c) < 2 {
      return nil, errors.New("failed parsing connection string due to unmatched key value separated by '='")
    }
    key := c[0]
    switch {
    case strings.EqualFold(key, "HostName"):
      u, err := url.Parse(c[1])
      if err != nil {
        return nil, errors.New("failed parsing connection string due to an incorrectly formatted Endpoint value")
      }
      hostSplits := strings.SplitN(c[1], ".", 2)
      if len(hostSplits) < 2 {
        return nil, errors.New("failed parsing connection string due to Endpoint value not containing a URL with a namespace and a suffix")
      }
      m.hostName = c[1]
      m.suffix = hostSplits[1]
      m.hubName = hostSplits[0]
    case strings.EqualFold(key, "DeviceId"):
      m.deviceID = c[1]
    case strings.EqualFold(key, "ModuleId"):
      m.moduleID = c[1]
    case strings.EqualFold(key, "SharedAccessKey"):
      m.sharedAccessKey = c[1]
    case strings.EqualFold(key, "SharedAccessKeyName"):
      m.sharedAccessKeyName = c[1]
    case strings.EqualFold(key, "SharedAccessSignature"):
      m.sharedAccessToken = c[1]
    case strings.EqualFold(key, "GatewayHostName"):
      m.gatewayHostName = c[1]
    }
  }
  m.isUsingX509 = strings.Contains(cs, "x509=true")

  if m.sharedAccessToken == "" {
    if m.hostName == "" {
      return nil, fmt.Errorf("key %q must not be empty", "HostName")
    }

    if m.sharedAccessKeyName == "" && m.deviceID == "" && m.moduleID == "" {
      return nil, fmt.Errorf("one of '%s', '%s' or '%s' must be specified", "SharedAccessKeyName", "DeviceId", "ModuleId")
    }

    if m.sharedAccessKey == "" {
      return nil, fmt.Errorf("key %q must not be empty", "SharedAccessKey")
    }
  } else {
    expired, err := isTokenExpired(m.sharedAccessToken)
    if err != nil {
      return nil, err
    } else if expired {
      return nil, errors.New("the token has expired")
    }
  }

  return m, nil
}
```
Combine this with what is already there and the connection string parsing becomes overly complicated. 

I understand from our CAT team that the GO IoT SDK is on the roadmap, but has no scheduled implementation.

Having said all of that, I understand if you want to "retract" your offer of making the event hub SDK work with an IoT Hub.

**Comment by devigned** [comment]
Check out what we do in the [Python SDK for Event Hubs for IoT message support](https://github.com/Azure/azure-event-hubs-python/blob/ff197f3156c6b522cb833e65bb6f77702accd1b3/azure/eventhub/client.py#L198-L225). It's not too bad.

There is a lot of device / service functionality in IoT that Event Hub messaging doesn't cover. I think the scope of this would just be connecting to the IoT provisioned Event Hub instance.

What do you think?

**Comment by talmdal** [comment]
Thanks,

Using the event hub and the amqp-common library, to wrap the connection and authentication would save a lot of futzing around with the variety of authentication, connection issues, token renewal, etc. if there was a way, once the connection was made to expose the amqp.client so additional sessions and links could be established to non-event hub topics (i.e. /methods/devicebound, /twin and /messages/devicebound) that would be useful.

Although, that would probably just take me back to the problem I'm having with direct methods (vcabbage/amqp issue)

My motivation behind all of this, in the absence of a MS supported Go IoT hub SDK, is to avoid using CGo wrapper around the C IoT hub SDK.  I even started down the path of porting the Java SDK to Go, but realized that was a lot of work and not something from a corporate perspective, we'd want go (personally, it would be a fun exercise)

I hope that answers your question.

**Comment by atecce** [comment]
> I see the issue. The connection string is in a different format than what is expected for Event Hubs. I will add a constructor to parse this and construct a Hub or a EventProcessorHost.
> 
> As for the message, that is due to the connection string for Event Hub requiring `Endpoint` as one of the keys. As you can see in the IoT connection string, it's actually `HostName`.

fwiw it's pretty straightforward to set Terraform output variables for `event_hub_events_endpoint`, `event_hub_events_path`, `shared_access_policy.0.key_name`, and `shared_access_policy.0.primary_key` and construct a Event Hub compatible connection string programmatically, which is what I'm doing [here](https://github.com/Azure/azure-event-hubs-go/issues/110)

**Comment by atecce** [comment]
should this be closed? arguably it's already solved at the transport layer [through Event Hub compatible endpoints](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin)

**Comment by atecce** [comment]
btw @devigned fwiw I construct it programmatically through tf output variables like this 

```go
func get(name string) string {
	stdout, err := exec.Command("terraform", "output", name).Output()
	if err != nil {
		println(err.Error())
		os.Exit(1)
	}

	return strings.TrimSuffix(string(stdout), "\n")
}```

...

```go
	endpoint := get("endpoint")
	sharedAccessKeyName := get("shared_access_key_name")
	sharedAccessKey := get("shared_access_key")
	entityPath := get("entity_path")

	hub, err := eventhub.NewHubFromConnectionString(
		"Endpoint=" + endpoint + ";" +
			"SharedAccessKeyName=" + sharedAccessKeyName + ";" +
			"SharedAccessKey=" + sharedAccessKey + ";" +
			"EntityPath=" + entityPath)
	if err != nil {
		println(err.Error())
		os.Exit(1)
	}
```

**Comment by devigned** [comment]
I'm going to close this issue, and create another to track improving the developer experience. This is not a fun experience at this point.
