### ISSUE TITLE
Interface that describes Hub

### ISSUE THREAD

**Issue by xbitres** [Azure/azure-event-hubs-go#98]
Having an interface that represents a Hub would allow for the developers to mock the Hub when testing.

Is there any other way to mock it?

**Comment by devigned** [comment]
I'm hesitant to add interface definitions for testing purposes. It seems like it would be better for application consuming the library to create its own abstraction and mock that abstraction.

I don't think I can layout the position better than @vcabbage has [here](https://github.com/vcabbage/amqp/issues/159#issuecomment-470336024).

With that said, I do like what is going on in https://github.com/google/go-cloud/blob/master/pubsub/driver/driver.go. I think that could be the abstraction layer to solve this problem.

**Comment by xbitres** [comment]
We kind of have the Sender interface in the current lib. However it is lacking the Close() method to be able to represent the Hub.

**Comment by devigned** [comment]
I'm going to close this issue for the reasons I pointed out above. However, I do believe the testing / mocking of this library for easier use in development should be easier. I'm open to ideas.
