### ISSUE TITLE
Expose "x-opt-enqueued-time" as part of event properties

### ISSUE THREAD

**Issue by ponsakthi** [Azure/azure-event-hubs-go#99]
### Environment
- OS: Windows10
- Go version: 1.12.1
- Version of Library: latest

Expose "x-opt-enqueued-time" as part of event properties. This will be useful on the eventprocessorhost receiver client to measure any lags or delays in processing

**Comment by devigned** [comment]
I like the way that we handled this in https://github.com/Azure/azure-service-bus-go with a mapstructure which will transform annotations into the `SystemProperties` structure which resides on `Message` struct (`Event` in this case) shown here https://github.com/Azure/azure-service-bus-go/blob/ca4ff1da9488f0ab8788dd85c5bf0217e8edd343/message.go#L69-L80. The transformation of annotations to `SystemProperties` occurs here https://github.com/Azure/azure-service-bus-go/blob/ca4ff1da9488f0ab8788dd85c5bf0217e8edd343/message.go#L476-L480.

@ponsakthi if you'd like to provide a PR, I'd be glad to review it and get it pulled in. Outside of that, I have a couple other items in the queue ahead of this and will get to it sometime in the upcoming month.

**Comment by aloysiustany** [comment]
@devigned Any progress on this ?

**Comment by devigned** [comment]
Sorry... this kept getting pushed down on the priority queue. I'll try to get it in tomorrow or Monday.

**Comment by devigned** [comment]
Should be available in `v1.3.0`. Thank you for your patience!
